# -*- coding: utf-8 -*-
"""CodeChef

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rAOR528dx37wLtBzeTRiSdpzn2C2ghNr
"""

# cook your dish here
n,k = map(int, input().split(" "))
arr =list(map(int, input().split(" ")))
if(k in arr):
    print(1)
else:
    print(-1)